package exceptionhandling;

public class Throw {

	public static void example() {
		throw new ArithmeticException("devide by o");
	}
	public static void main(String[] args) {
      example();
	}
}